# Generated by Django 6.1 on 2026-08-16 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_remove_post_updated_at_post_likes_alter_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('academic', '🎓 학업/성적'), ('career', '🎯 진로/진학'), ('friends', '🤝 친구/대인관계'), ('love', '💌 이성/연애'), ('family', '🏠 가족'), ('etc', '💭 기타')], default='etc', max_length=20),
        ),
    ]
