# Generated by Django 6.1 on 2026-08-16 11:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_post_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='sads',
            field=models.ManyToManyField(blank=True, related_name='sad_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='thumbs',
            field=models.ManyToManyField(blank=True, related_name='thumb_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
