# Generated by Django 6.1 on 2026-08-16 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_post_sads_post_thumbs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('worry', '고민'), ('daily', '일상'), ('etc', '기타')], default='etc', max_length=20),
        ),
    ]
