# Generated by Django 6.1 on 2026-08-16 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('love', '연애'), ('friend', '친구'), ('family', '가족'), ('study', '학업/진로'), ('etc', '기타')], default='etc', max_length=20),
        ),
    ]
